// apps/react-app-vite/src/app/app.tsx
import { ReactViteUiButton } from '@storybook-nx-show/react/vite/ui/button';
import { ReactViteUiBanner } from '@storybook-nx-show/react/vite/ui/banner';

export function App() {
  return (
    <>
      <ReactViteUiBanner
        backgroundColor="#FF00FF66"
        text="This is a banner"
        borderColor="#f3f3f3"
        width={350}
        height={50}
        borderWidth={2}
      />

      <ReactViteUiButton text="Click me" color="#f300fe" disabled={false} />
    </>
  );
}

export default App;

// apps/ng-app/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'storybook-nx-show-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent {}

<storybook-nx-show-banner
  [text]="'Hello world'"
  [backgroundColor]="'#FF00FF66'"
  [borderColor]="'#FF00FF'"
  [borderWidth]="4"
  [width]="350"
  [height]="50"
></storybook-nx-show-banner>
<storybook-nx-show-button
  [text]="'Hello world'"
  [color]="'#FF00FF66'"
  [disabled]="false"
></storybook-nx-show-button>
