// apps/next-app/pages/_app.tsx
import { AppProps } from 'next/app';
import { NextUiBanner } from '@storybook-nx-show/next/ui/banner';
import { NextUiButton } from '@storybook-nx-show/next/ui/button';

function CustomApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <NextUiBanner
        backgroundColor="#FF00FF66"
        text="This is a banner"
        borderColor="#FF00FF"
        width={350}
        height={50}
        borderWidth={2}
      />

      <NextUiButton text="Click me" color="#f300fe" disabled={false} />
    </>
  );
}

export default CustomApp;

// apps/ng-app/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'storybook-nx-show-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent {}

<storybook-nx-show-banner
  [text]="'Hello world'"
  [backgroundColor]="'#FF00FF66'"
  [borderColor]="'#FF00FF'"
  [borderWidth]="4"
  [width]="350"
  [height]="50"
></storybook-nx-show-banner>
<storybook-nx-show-button
  [text]="'Hello world'"
  [color]="'#FF00FF66'"
  [disabled]="false"
></storybook-nx-show-button>
